# Generated by Django 5.1.7 on 2025-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(max_length=255, verbose_name='Картинка'),
        ),
    ]
