# Generated by Django 5.1.7 on 2025-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api_app', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(max_length=255, null=True, verbose_name='Картинка'),
        ),
    ]
